name: Azure Login via azure cli

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  azure-login-and-resource-access:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{  secrets['AZURE_CLIENT_ID']}}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}
     
 

          
          
