name: Azure Login via azure cli

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  
permissions:
  id-token: write
  contents: read
jobs:
  azure-login-and-resource-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 
 
      - name: Azure login
        env:
           client_id: id
           
        uses: azure/login@v2
        with:
          client-id: ${{  secrets[format('azure_client_{0}',  inputs.environment )] }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}
     
    
      # - name: cmd
      #   run: |
      #       cd ./personal_testing
      #       terraform init

          
          
