name: secretes_with backend.tf

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
  
   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secretes.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}

      - name: Terraform replace  azure creds
        env:
          client-id: ${{ secretes.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}
        run: | 
         sed -i """s/"client_id_value"/"$client-id"/g""" backend.tf
          sed -i """s/"tenant_id_value"/"$tenant-id"/g""" backend.tf
          sed -i """s/"subsription_id_value"/"$subsription-id"/g""" backend.tf
          cat backend.tf
        
        
    

      - name: terraform  init & apply & destroy
        env: 
          TF_VAR_github_token: ${{ secrets.ga_token}}
        run: |
           terraform init
           terraform apply -auto-approve
           terraform destroy -auto-approve
     
      
