name: secretes_with backend.tf

on:
  workflow_dispatch:
    # inputs:
    #   environment:
    #     required: true
    #     type: string
  
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
  
   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets['AZURE_CLIENT_ID'] }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}

      # - name: Passing Azure creds to backend.tf
      #   env:
      #     client_id: ${{  secrets['AZURE_CLIENT_ID']}}
      #     tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription_id: ${{ secrets.AZURE_SUB_ID }}
      #   run: | 
      #     sed -i """s/"client_id_value"/"$client_id"/g""" backend.tf
      #     sed -i """s/"tenant_id_value"/"$tenant_id"/g""" backend.tf
      #     sed -i """s/"subscription_id_value"/"$subscription_id"/g""" backend.tf
        
        
      - name: terraform  init & apply & destroy
        env: 
          ARM_CLIENT_ID: ${{ secrets['AZURE_CLIENT_ID'] }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUB_ID }}
        run: |
           terraform init -backend-config=backend.config
        # terraform apply -auto-approve
        # terraform destroy -auto-approve
     
      
