
name: Deploy backend_infra
on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:     
  create-backend-infra:   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
       # AZ CLI Login using OIDC Federated credential
      - name: Azure login - ${{ inputs.environment }}
        uses: azure/login@v2.1.0
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }} 
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
      - name: Pipelines Terraform initialize
       
        run: |
            cd ./create_backend
            terraform init
            terraform plan
            terraform apply -auto-approve

