name: Snowflake Workflow

on:
  workflow_dispatch:

jobs:
  snowflake-workflow:
    runs-on: ubuntu-latest
    env:
      aname: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      uname: ${{ secrets.SNOWFLAKE_USER }}
      password: ${{ secrets.SNOWFLAKE_PASSWORD }}
      
    # SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
    # SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
    # SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
     
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-python@v5
       with:
          python-version: '3.12' 

     - name: Install requirements
       run: pip install -r src/requirement.txt
      
     - name: snowflake connect
       run: python src/snowflake_connect.py


