name: Set Environment Variables

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  set_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        uses: avijitsamantaray/Devops/actions@main
        with:
          variables: |
            MY_VAR1=value1
            MY_VAR2=value2
