name: Set Environment Variables

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  set_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set environment variables
        uses: avijitsamantaray/custom-actions@main

      - name: echo names
        run : echo $name
