name: Deploy Foundation Infra

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  
permissions:
  id-token: write
  contents: read


jobs:
  terraform:
    runs-on: ubuntu-latest
    
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: show
        env:
         # sub_id: format('hi_{0}',  ${{ inputs.environment }})
         sub_id: $ {{ vars.demo}}
        run :
            echo  "$sub_id"
          
        
        
        

      
